services:
  - type: web
    name: swiss-crm-project
    runtime: docker
    plan: free
    dockerfilePath: ./offer/1/Dockerfile
    dockerContext: ./offer/1
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: RUN_MIGRATIONS
        value: "false"
